version: '2.4'

services:
  code:
    image: 'shops'
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    volumes:
      - './shops:/code/shops'
    ports:
      - 8000:8000
    depends_on:
      - mongo

  mongo:
    image: 'mongo:4.4.0-rc10-bionic'
    ports:
      - 27017:27017
